stages:
  - test

unit_tests:
  stage: test
  script:
    - pnpm run test:unit

integration_tests:
  stage: test
  needs: ["unit_tests"] # Attend que les tests unitaires soient finis
  script:
    - pnpm run test:integration

